# .gitpod.yml
tasks:
  - name: Install AWS CLI
    env:
      AWS_REGION:   # You can change or remove this
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      rm -rf aws awscliv2.zip
      echo "✅ AWS CLI installed successfully"

vscode:
  extensions:
    - 42Crunch.vscode-openapi