version: "3.8"

services:
  backend-flask:
    image: 19911992/backendflask4
    volumes:
      - ../backend-flask:/backend-flask
    environment:
      FRONTEND_URL: "${FRONTEND_URL}"
      BACKEND_URL: "${BACKEND_URL}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io"
      OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=${HONEYCOMB_API_KEY}"
      OTEL_SERVICE_NAME: "${HONEYCOMB_SERVICE_NAME}"
      AWS_XRAY_URL: "*4567-${CODESPACE_NAME}.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}*"
      AWS_XRAY_DAEMON_ADDRESS: "xray-daemon:2000"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    ports:
      - "4567:4567"
    networks:
      - aws-bootcamp
   
  frontend-react-js:
    image: 19911992/frontend-react2
    volumes:
      - ../frontend-react-js:/frontend-react-js
    environment:
      BACKEND_URL: "${BACKEND_FRONT}"
    ports:
      - "3000:3000"
    networks:
      - aws-bootcamp
   
  xray-daemon:
    image: "amazon/aws-xray-daemon"
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "us-east-1"
    command:
      - "xray -o -b xray-daemon:2000"
    ports:
      - 2000:2000/udp
    networks:
      - aws-bootcamp

networks:
  aws-bootcamp:
    driver: bridge